-- dialect: postgresql
ALTER TABLE "accounts" ALTER COLUMN "id" TYPE integer USING "id"::integer;
ALTER TABLE "accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('accounts', 'id'), COALESCE((SELECT MAX("id") FROM "accounts"), 0) + 1, false);